### ISSUE TITLE
LLMFramework Interface

### ISSUE THREAD

**Issue by kavitharaju** [BibleNLP/assistant.bible#11]
For class implementations of Vanilla and Langchain frameworks.
```
class LLMFrameworkInterface:
    '''Interface for embedding technology and its use'''
    api_key: str
    model_name: str
    api_object = None
    llm = None
    def __init__(self, key:str, **kwargs) -> None:
        '''Sets the API key and initializes library objects if any'''
        self.api_key = key
    def generate_text(self,
    	query:str,
    	chat_history:List[Tuple[str,str]]=None,
    	# context_docs: List[schema.Document]=None
        **kwargs) -> dict:
        '''Prompt completion for QA or Chat reponse, based on specific documents, if provided'''
        return {}
```

for the response object of generate_text(), in langchain side we get 
```
{ question: ...., answer: ...., source_documents: [ {page_content:..., metadata:{ source: ...}]
```
Should we standardize that or customize it differently?

**Comment by woodwardmw** [comment]
@kavitharaju I think that looks good. Technically you shouldn't have to return the question, since I don't think that would change from the paramater being inputted into `generate_text`, right? But if it's simpler to return it along with the answer, that's fine.

Do we also want to add an input parameter for `language`? In my demo I have a `translate()` function, which translates to English and also identifies the language of the user query, and then within `generate_text` my LLM prompt would ask the LLM to respond in that language.

**Comment by woodwardmw** [comment]
@kavitharaju Is `generate_text` an `@abstractmethod` that gets implemented by each ChildClass? Or are we defining it here in `LLMFrameworkInterface`?

**Comment by kavitharaju** [comment]
Yes, generate_text() is expected to be implemented by ChildClasses. So,may be we could do required PROMPT engineering within there if we want to do more advanced stuff, like getting LLM to answer in a different language.

About having a translate() step, how do you do it in your demo? Are you depending on LLM itself for this language idenfification and translation or is it a different component ? Depending on that we could either have (a) one more class method in this LLMFramework interface or (b) a different interface altogether for translation that gets added to the chat-pipeline... I think option b, would be better, and will allow us to choose between different technologies like we do for other components...

**Comment by woodwardmw** [comment]
Yes, I think option b is probably better, to have it separate. In my demo I'm using the google translate API, which translates to English and does language identification. But obviously it would be good to have the possibility of using other translation options too, so maybe we could have a translation interface.
