### ISSUE TITLE
UI gets redirected to /NaN

### ISSUE THREAD

**Issue by kavitharaju** [BibleNLP/assistant.bible#74]
This issue occurs when,
1. Bot returns an error in previous exchange and then user types in next question
2. When there is issue with login token( may be token expired)

- [ ] Disable input when user is not logged in

**Comment by ryderwishart** [comment]
We should disable the input box when the user is not logged in.

**Comment by woodwardmw** [comment]
I think the underlying issue here is that this happens when the connection is closed, and then the user sends a message. So I think we need to:
1) handle that situation more gracefully
2) disable the input when the connection is closed.
